//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlisansProje2
{
    using System;
    using System.Collections.Generic;
    
    public partial class il
    {
        public il()
        {
            this.ilces = new HashSet<ilce>();
        }
    
        public int ID { get; set; }
        public string ilAdi { get; set; }
    
        public virtual ICollection<ilce> ilces { get; set; }
    }
}
