//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlisansProje2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilan
    {
        public int ID { get; set; }
        public string baslik { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> metrekare { get; set; }
        public Nullable<System.DateTime> oluşturmaTarihi { get; set; }
        public Nullable<int> semtID { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<int> fotoID { get; set; }
        public Nullable<int> turID { get; set; }
        public Nullable<int> detay_ID { get; set; }
    
        public virtual foto foto { get; set; }
        public virtual ilanDetay ilanDetay { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual semt semt { get; set; }
        public virtual tur tur { get; set; }
    }
}
