//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlisansProje2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        public ilce()
        {
            this.semts = new HashSet<semt>();
        }
    
        public int ID { get; set; }
        public string ilceAdi { get; set; }
        public Nullable<int> ilID { get; set; }
    
        public virtual il il { get; set; }
        public virtual ICollection<semt> semts { get; set; }
    }
}
