//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlisansProje2
{
    using System;
    using System.Collections.Generic;
    
    public partial class semt
    {
        public semt()
        {
            this.ilans = new HashSet<ilan>();
        }
    
        public int ID { get; set; }
        public string semtAdi { get; set; }
        public Nullable<int> ilceID { get; set; }
    
        public virtual ICollection<ilan> ilans { get; set; }
        public virtual ilce ilce { get; set; }
    }
}
